version: "3.5"
services: 
  server:
    build: server/
    environment:
      - VIRTUAL_HOST=api.waifucollector.com
      - LETSENCRYPT_HOST=api.waifucollector.com
      - LETSENCRYPT_EMAIL=kirchler.lion@gmail.com
    networks:
      - default

  client:
    build: client/
    environment:
      - VIRTUAL_HOST=waifucollector.com
      - LETSENCRYPT_HOST=waifucollector.com
      - LETSENCRYPT_EMAIL=kirchler.lion@gmail.com
    networks:
      - default

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: waifucollector
      # this mysql database should only be exposed to the other services
      MYSQL_ROOT_PASSWORD: waifu
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql:/var/lib/mysql
    networks:
      - default
    restart: always

networks:
  default:
    external: true
    name: proxy
