version: "3.5"
services: 
  server:
    build: rust/
    environment:
      - VIRTUAL_HOST=api.waifucollector.com
      - LETSENCRYPT_HOST=api.waifucollector.com
      - LETSENCRYPT_EMAIL=kirchler.lion@gmail.com
    networks:
      - default

  client:
    build: react_app/
    environment:
      - VIRTUAL_HOST=waifucollector.com
      - LETSENCRYPT_HOST=waifucollector.com
      - LETSENCRYPT_EMAIL=kirchler.lion@gmail.com
    networks:
      - default

networks:
  default:
    external: true
    name: proxy
