INSERT INTO cards (cid, cname, ctid, cimage) VALUES (1, 'Rem', 1, 'Card_Rem.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (2, 'ZeroTwo', 2, 'Card_ZeroTwo.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (3, 'Chika', 3, 'Card_Chika.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (4, 'Megumin', 4, 'Card_Megumin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (5, 'Akame', 5, 'Card_Akame.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (6, 'Annie Leonhardt', 6, 'Card_AnnieLeonhardt.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (7, 'Lucy Heartfilia', 7, 'Card_LucyHeartfilia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (8, 'Ram', 1, 'Card_Ram.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (9, 'Kashiwazaki Sena', 8, 'Card_KashiwazakiSena.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (10, 'Ayanami Rei', 9, 'Card_AyanamiRei.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (11, 'Mary Saotome', 10, 'Card_MarySaotome.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (12, 'Rukia Kuchiki', 11, 'Card_RukiaKuchiki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (13, 'Bishamonten', 12, 'Card_Bishamonten.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (14, 'Ikumi Mito', 13, 'Card_IkumiMito.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (15, 'Ino Yamanaka', 14, 'Card_InoYamanaka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (16, 'Chelsea', 5, 'Card_Chelsea.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (17, 'Emilia', 1, 'Card_Emilia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (18, 'Esdeath', 5, 'Card_Esdeath.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (19, 'Himiko Toga', 15, 'Card_HimikoToga.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (20, 'Jirou Kyouka', 15, 'Card_JirouKyouka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (21, 'Ikaros', 16, 'Card_Ikaros.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (22, 'Shiina Mashiro', 17, 'Card_ShiinaMashiro.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (23, 'Isla', 18, 'Card_Isla.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (24, 'Kanade Tachibana', 19, 'Card_KanadeTachibana.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (25, 'Kirisaki Chitoge', 20, 'Card_KirisakiChitoge.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (26, 'Miss Valentine', 21, 'Card_MissValentine.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (27, 'Kurome', 5, 'Card_Kurome.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (28, 'Kurumi Tokisaki', 22, 'Card_KurumiTokisaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (29, 'Mizore', 23, 'Card_Mizore.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (30, 'Nami', 21, 'Card_Nami.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (31, 'Lieselotte Sherlock', 24, 'Card_LieselotteSherlock.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (32, 'Ruri', 25, 'Card_Ruri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (33, 'Kirigaya Suguha', 26, 'Card_KirigayaSuguha.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (34, 'Lan Fan', 27, 'Card_LanFan.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (35, 'Leone', 5, 'Card_Leone.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (36, 'Mio Naruse', 28, 'Card_MioNaruse.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (37, 'Satsuki Momoi', 29, 'Card_SatsukiMomoi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (38, 'Koneko Toujou', 30, 'Card_KonekoToujou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (39, 'Erza Scarlet', 7, 'Card_ErzaScarlet.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (40, 'Nao Tomori', 31, 'Card_NaoTomori.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (41, 'Xenovia', 30, 'Card_Xenovia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (42, 'Raphtalia', 32, 'Card_Raphtalia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (43, 'Rei Miyamoto', 33, 'Card_ReiMiyamoto.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (44, 'Rindo Kobayashi', 13, 'Card_RindoKobayashi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (45, 'Erina Nakiri', 13, 'Card_ErinaNakiri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (46, 'Nakiri Alice', 13, 'Card_NakiriAlice.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (47, 'Temari', 14, 'Card_Temari.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (48, 'Tsunade', 14, 'Card_Tsunade.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (49, 'Jabami Yumeko', 10, 'Card_JabamiYumeko.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (50, 'Kirai Momobami', 10, 'Card_KiraiMomobami.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (51, 'Alice Zuberg', 26, 'Card_AliceZuberg.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (52, 'C18', 35, 'Card_C18.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (53, 'Astil Manuscript', 24, 'Card_AstilManuscript.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (54, 'Rachel Gardner', 36, 'Card_RachelGardner.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (55, 'Camie Utsumishi', 15, 'Card_CamieUtsumishi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (56, 'C C', 37, 'Card_CC.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (57, 'Darkness', 4, 'Card_Darkness.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (58, 'Elaine', 38, 'Card_Elaine.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (59, 'Papi', 39, 'Card_Papi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (60, 'Rachnera Arachnera', 39, 'Card_RachneraArachnera.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (61, 'Asia Argento', 30, 'Card_AsiaArgento.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (62, 'Irina Jelavic', 40, 'Card_IrinaJelavic.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (63, 'Boa Hancock', 21, 'Card_BoaHancock.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (64, 'Historia Reiss', 6, 'Card_HistoriaReiss.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (65, 'Hanabi Hyuga', 14, 'Card_HanabiHyuga.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (66, 'Kaori Miyazono', 41, 'Card_KaoriMiyazono.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (67, 'Kurumu Kurono', 23, 'Card_KurumuKurono.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (68, 'Lisesharte Atismata', 42, 'Card_LisesharteAtismata.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (69, 'Moka Akashiya', 23, 'Card_MokaAkashiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (70, 'Ririka Momobami', 10, 'Card_RirikaMomobami.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (71, 'Natsuki Mogi', 43, 'Card_NatsukiMogi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (72, 'Mikasa Ackermann', 6, 'Card_MikasaAckermann.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (73, 'Aqua', 4, 'Card_Aqua.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (74, 'Shokuhou Misaki', 44, 'Card_ShokuhouMisaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (75, 'Mikoto Misaka', 44, 'Card_MikotoMisaka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (76, 'Kanzaki Kaori', 45, 'Card_KanzakiKaori.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (77, 'Julis Riessfeld', 46, 'Card_JulisRiessfeld.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (78, 'Mine', 5, 'Card_Mine.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (79, 'Toudou Kirin', 46, 'Card_ToudouKirin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (80, 'Claudia Enfield', 46, 'Card_ClaudiaEnfield.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (81, 'Sasamiya Saya', 46, 'Card_SasamiyaSaya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (82, 'Toka Kirishima', 47, 'Card_TokaKirishima.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (83, 'Tohru', 48, 'Card_Tohru.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (84, 'Kanna Kamui', 48, 'Card_KannaKamui.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (85, 'Lucoa', 48, 'Card_Lucoa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (86, 'Elma', 48, 'Card_Elma.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (87, 'Ichigo', 2, 'Card_Ichigo.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (88, 'Runa Yomozuki', 10, 'Card_RunaYomozuki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (89, 'Yuriko Nishinotouin', 10, 'Card_YurikoNishinotouin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (90, 'Yumemite Yumemi', 10, 'Card_YumemiteYumemi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (91, 'Shizue Izawa', 50, 'Card_ShizueIzawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (92, 'Rias Gremory', 30, 'Card_RiasGremory.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (93, 'Hinata Hyuga', 14, 'Card_HinataHyuga.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (94, 'Asuna Yuuki', 26, 'Card_AsunaYuuki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (95, 'Chizuru Mizuhara', 51, 'Card_ChizuruMizuhara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (96, 'Ruka Sarashina', 51, 'Card_RukaSarashina.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (97, 'Mami Nanami', 51, 'Card_MamiNanami.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (98, 'Sumi Sakurasawa', 51, 'Card_SumiSakurasawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (99, 'Rin Tohsaka', 52, 'Card_RinTohsaka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (100, 'Misa Amane', 53, 'Card_MisaAmane.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (101, 'Shinoa Hiragi', 54, 'Card_ShinoaHiragi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (102, 'Nezuko Kamado', 55, 'Card_NezukoKamado.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (103, 'Saber', 52, 'Card_ArtoriaPendragon.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (104, 'Violet Evergarden', 56, 'Card_VioletEvergarden.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (105, 'Yuna', 57, 'Card_Yuna.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (106, 'Momoka Sonokawa', 58, 'Card_MomokaSonokawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (107, 'Miou Ootori', 58, 'Card_MiouOotori.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (108, 'Maya Kyodo', 58, 'Card_MayaKyodo.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (109, 'Urara Kasugano', 58, 'Card_UraraKasugano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (110, 'Yui', 19, 'Card_Yui.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (111, 'Yuri Nakamura', 19, 'Card_YuriNakamura.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (112, 'Eri Shiina', 19, 'Card_EriShiina.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (113, 'Hestia', 59, 'Card_Hestia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (114, 'Yamato Mikoto', 59, 'Card_YamatoMikoto.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (115, 'Sanjouno Haruhime', 59, 'Card_SanjounoHaruhime.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (116, 'Ais Wallenstein', 59, 'Card_AisWallenstein.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (117, 'Syr Flova', 59, 'Card_SyrFlova.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (118, 'Ryuu Lion', 59, 'Card_RyuuLion.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (119, 'Eina Tulle', 59, 'Card_EinaTulle.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (120, 'Kaguya Shinomiya', 3, 'Card_KaguyaShinomiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (121, 'Mai Sakurajima', 60, 'Card_MaiSakurajima.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (122, 'Kaname Arisugawa', 61, 'Card_KanameArisugawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (123, 'Aya Arisugawa', 61, 'Card_AyaArisugawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (124, 'Tsukasa Tsukuyomi', 61, 'Card_TsukasaTsukuyomi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (125, 'Maki Oze', 62, 'Card_MakiOze.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (126, 'Noel Niihashi', 11, 'Card_NoelNiihashi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (127, 'Shiba Miyuki', 63, 'Card_ShibaMiyuki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (128, 'Sayaka Kirasaka', 64, 'Card_SayakaKirasaka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (129, 'Vanessa Anoteca', 65, 'Card_VanessaAnoteca.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (130, 'Elaina', 66, 'Card_Elaina.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (131, 'Echidna', 1, 'Card_Echidna.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (132, 'Noelle Silva', 65, 'Card_NoelleSilva.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (133, 'Charlotte Roselei', 65, 'Card_CharlotteRoselei.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (134, 'Nero', 65, 'Card_Nero.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (135, 'Mimosa Vermillion', 65, 'Card_MimosaVermillion.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (136, 'Hana Uzaki', 67, 'Card_HanaUzaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (137, 'Ichika Nakano', 68, 'Card_IchikaNakano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (138, 'Nino Nakano', 68, 'Card_NinoNakano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (139, 'Miku Nakano', 68, 'Card_MikuNakano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (140, 'Yotsuba Nakano', 68, 'Card_YotsubaNakano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (141, 'Itsuki Nakano', 68, 'Card_ItsukiNakano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (142, 'Hori Kyouko', 69, 'Card_HoriKyouko.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (143, 'Cyan', 70, 'Card_Cyan.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (144, 'Kohaku', 25, 'Card_Kohaku.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (145, 'Shinobu Oshino', 71, 'Card_ShinobuOshino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (146, 'Suruga Kanbaru', 71, 'Card_SurugaKanbaru.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (147, 'Tsubasa Hanekawa', 71, 'Card_TsubasaHanekawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (148, 'Ougi Oshino', 71, 'Card_OugiOshino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (149, 'Izuko Gaen', 71, 'Card_IzukoGaen.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (150, 'Ryuko Matoi', 72, 'Card_RyukoMatoi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (151, 'Satsuki Kiryuin', 72, 'Card_SatsukiKiryuin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (152, 'Nui Harime', 72, 'Card_NuiHarime.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (153, 'Mako Mankanshoku', 72, 'Card_MakoMankanshoku.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (154, 'Nonon Jakuzure', 72, 'Card_NononJakuzure.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (155, 'Kokoro', 2, 'Card_Kokoro.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (156, 'Miku', 2, 'Card_Miku.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (157, 'Ikuno', 2, 'Card_Ikuno.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (158, '001', 2, 'Card_001.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (159, 'Aina Ardebit', 73, 'Card_AinaArdebit.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (160, 'Phosphophyllite', 74, 'Card_Phosphophyllite.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (161, 'Cinnabar', 74, 'Card_Cinnabar.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (162, 'Diamond', 74, 'Card_Diamond.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (163, 'Swindler', 75, 'Card_Swindler.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (164, 'Seras Victoria', 76, 'Card_SerasVictoria.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (165, 'Shiki Ryougi', 77, 'Card_ShikiRyougi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (166, 'Asuka Langley Sohryu', 9, 'Card_AsukaLangleySohryu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (167, 'Misato Katsuragi', 9, 'Card_MisatoKatsuragi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (168, 'Stephanie Dola', 78, 'Card_StephanieDola.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (169, 'Jibril', 78, 'Card_Jibril.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (170, 'Ochako Uraraka', 15, 'Card_OchakoUraraka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (171, 'Tsuyu Asui', 15, 'Card_TsuyuAsui.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (172, 'Momo Yaoyorozu', 15, 'Card_MomoYaoyorozu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (173, 'Nejire Hado', 15, 'Card_NejireHado.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (174, 'Mei Hatsume', 15, 'Card_MeiHatsume.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (175, 'Roxy Migurdia', 79, 'Card_RoxyMigurdia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (176, 'Eris Boreas Greyrat', 79, 'Card_ErisBoreasGreyrat.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (177, 'Ghislaine Dedoldia', 79, 'Card_GhislaineDedoldia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (178, 'Sylphiette', 79, 'Card_Sylphiette.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (179, 'Robert E O Speedwagon', 80, 'Card_RobertEOSpeedwagon.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (180, 'Sakura Matou', 52, 'Card_SakuraMatou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (181, 'Yuuna Yunohana', 81, 'Card_YuunaYunohana.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (182, 'Amane Suou', 82, 'Card_AmaneSuou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (183, 'Yumiko Sakaki', 82, 'Card_YumikoSakaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (184, 'Michiru Matsushima', 82, 'Card_MichiruMatsushima.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (185, 'Sachi Komine', 82, 'Card_SachiKomine.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (186, 'Makina Irisu', 82, 'Card_MakinaIrisu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (187, 'Kazuki Kazami', 82, 'Card_KazukiKazami.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (188, 'Akeno Himejima', 30, 'Card_AkenoHimejima.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (189, 'Ravel Phoenix', 30, 'Card_RavelPhoenix.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (190, 'Albedo', 83, 'Card_Albedo.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (191, 'Lisa Lisa', 80, 'Card_LisaLisa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (192, 'Trish Una', 80, 'Card_TrishUna.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (193, 'Yukako Yamagishi', 80, 'Card_YukakoYamagishi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (194, 'Yoruichi Shihoin', 11, 'Card_YoruichiShihoin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (195, 'Nemu Kurotsuchi', 11, 'Card_NemuKurotsuchi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (196, 'Sode no Shirayuki', 11, 'Card_SodenoShirayuki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (197, 'Nelliel Tu Odelschwanck', 11, 'Card_NellielTuOdelschwanck.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (198, 'Tier Harribel', 11, 'Card_TierHarribel.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (199, 'Cyan Sung-Sun', 11, 'Card_CyanSung-Sun.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (200, 'Lisa Yadomaru', 11, 'Card_LisaYadomaru.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (201, 'Hiyori Sarugaki', 11, 'Card_HiyoriSarugaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (202, 'Charmy Pappitson', 65, 'Card_CharmyPappitson.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (203, 'Vanica Zogratis', 65, 'Card_VanicaZogratis.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (204, 'Fana', 65, 'Card_Fana.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (205, 'Sister Lily', 65, 'Card_SisterLily.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (206, 'Dorothy Unsworth', 65, 'Card_DorothyUnsworth.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (207, 'Sol Marron', 65, 'Card_SolMarron.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (208, 'Nico Robin', 21, 'Card_NicoRobin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (209, 'Shirahoshi', 21, 'Card_Shirahoshi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (210, 'Nefertari Vivi', 21, 'Card_NefeltariVivi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (211, 'Carrot', 21, 'Card_Carrot.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (212, 'Charlotte Pudding', 21, 'Card_CharlottePudding.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (213, 'Kozuki Hiyori', 21, 'Card_KozukiHiyori.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (214, 'Marguerite', 21, 'Card_Marguerite.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (215, 'Tomoko Kuroki', 84, 'Card_TomokoKuroki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (216, 'Yuu Naruse', 84, 'Card_YuuNaruse.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (217, 'Rem Galleu', 85, 'Card_RemGalleu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (218, 'Setsuna', 86, 'Card_Setsuna.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (219, 'Rikka Takanashi', 87, 'Card_RikkaTakanashi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (220, 'Satone Shichimiya', 87, 'Card_SatoneShichimiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (221, 'Kumin Tsuyuri', 87, 'Card_KuminTsuyuri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (222, 'Yoshino Himekawa', 22, 'Card_YoshinoHimekawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (223, 'Itsuka Kotori', 22, 'Card_ItsukaKotori.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (224, 'Kaguya Yamai', 22, 'Card_KaguyaYamai.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (225, 'Yamai Kazamachi', 22, 'Card_YamaiKazamachi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (226, 'Tohka Yatogami', 22, 'Card_TohkaYatogami.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (227, 'Mei Misaki', 88, 'Card_MeiMisaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (228, 'Himeka Akishino', 89, 'Card_HimekaAkishino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (229, 'Chiwa Harusaki', 89, 'Card_ChiwaHarusaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (230, 'Kaede Azusagawa', 60, 'Card_KaedeAzusagawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (231, 'Onna Shinkan', 90, 'Card_OnnaShinkan.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (232, 'Erufu', 90, 'Card_Erufu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (233, 'Shalltear Bloodfallen', 83, 'Card_ShalltearBloodfallen.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (234, 'Reimi Sugimoto', 80, 'Card_ReimiSugimoto.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (235, 'Erina Pendleton', 80, 'Card_ErinaPendleton.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (236, 'Suzie Q', 80, 'Card_SuzieQ.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (237, 'Elsha Lean', 92, 'Card_ElshaLean.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (238, 'Atlee Ariel', 92, 'Card_AtleeAriel.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (239, 'Ren Sin', 92, 'Card_RenSin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (240, 'Ai Ohto', 93, 'Card_AiOhto.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (241, 'Holo', 94, 'Card_Holo.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (242, 'Yuria', 95, 'Card_Yuria.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (243, 'Tou', 95, 'Card_Tou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (244, 'Mamiya', 95, 'Card_Mamiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (245, 'Ilulu', 48, 'Card_Ilulu.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (246, 'Yuno Gasai', 96, 'Card_YunoGasai.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (247, 'Minene Uryuu', 96, 'Card_MineneUryuu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (248, 'Yin', 97, 'Card_Yin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (249, 'Amber', 97, 'Card_Amber.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (250, 'Misaki Kirihara', 97, 'Card_MisakiKirihara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (251, 'Mumei', 98, 'Card_Mumei.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (252, 'Kotoko Iwanaga', 99, 'Card_KotokoIwanaga.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (253, 'Saki Yumihara', 99, 'Card_SakiYumihara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (254, 'Misaki Nakahara', 100, 'Card_MisakiNakahara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (255, 'Ayame Kajou', 101, 'Card_AyameKajou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (256, 'Anna Nishikinomiya', 101, 'Card_AnnaNishikinomiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (257, 'Mikoto Urabe', 102, 'Card_MikotoUrabe.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (258, 'Koko Hekmatyar', 103, 'Card_KokoHekmatyar.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (259, 'Sakura Hibiki', 104, 'Card_SakuraHibiki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (260, 'Soryuin Akemi', 104, 'Card_SoryuinAkemi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (261, 'Zina Void', 104, 'Card_ZinaVoid.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (262, 'Uehara Ayaka', 104, 'Card_UeharaAyaka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (263, 'Akiko Yosano', 105, 'Card_AkikoYosano.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (264, 'Kyoko Izumi', 105, 'Card_KyokoIzumi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (265, 'Naomi Tanizaki', 105, 'Card_NaomiTanizaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (266, 'Ichiyo Higuchi', 105, 'Card_IchiyoHiguchi.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (267, 'Clementine', 83, 'Card_Clementine.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (268, 'Special Week', 91, 'Card_SpecialWeek.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (269, 'Vodka', 91, 'Card_Vodka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (270, 'Silence Suzuka', 91, 'Card_SilenceSuzuka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (271, 'Tokai Teio', 91, 'Card_TokaiTeio.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (272, 'Gold Ship', 91, 'Card_GoldShip.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (273, 'Daiwa Scarlet', 91, 'Card_DaiwaScarlet.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (274, 'Ohana Matsumae', 106, 'Card_OhanaMatsumae.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (275, 'Black Rabbit', 107, 'Card_BlackRabbit.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (276, 'Honey', 108, 'Card_Honey.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (277, 'Rena Ryuuguu', 109, 'Card_RenaRyuuguu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (278, 'Mion Sonozaki', 109, 'Card_MionSonozaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (279, 'Shion Sonozaki', 109, 'Card_ShionSonozaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (280, 'Satoko Houjou', 109, 'Card_SatokoHoujou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (281, 'Rika Furude', 109, 'Card_RikaFurude.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (282, 'Inori Yuzuriha', 49, 'Card_InoriYuzuriha.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (283, 'Nashetania Loei Piena Augustra', 110, 'Card_NashetaniaLoeiPienaAugustra.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (284, 'Flamie Speeddraw', 110, 'Card_FlamieSpeeddraw.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (285, 'Maple', 111, 'Card_Maple.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (286, 'Fubuki Sakuragasaki', 112, 'Card_FubukiSakuragasaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (287, 'Chtholly Nota Seniorious', 113, 'Card_ChthollyNotaSeniorious.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (288, 'Clare', 114, 'Card_Clare.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (289, 'Yoko Littner', 115, 'Card_YokoLittner.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (290, 'Yue', 116, 'Card_Yue.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (291, 'Shea Haulia', 116, 'Card_SheaHaulia.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (292, 'Faye Valentine', 117, 'Card_FayeValentine.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (293, 'Judy', 117, 'Card_Judy.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (294, 'Ristarte', 118, 'Card_Ristarte.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (295, 'Perona', 21, 'Card_Perona.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (296, 'Lain', 119, 'Card_Lain.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (297, 'Rea Sanka', 120, 'Card_ReaSanka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (298, 'Sempai', 121, 'Card_Sempai.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (299, 'Saki', 121, 'Card_Saki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (300, 'Madara', 121, 'Card_Madara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (301, 'Bulma', 35, 'Card_Bluma.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (302, 'Winry Rockbell', 27, 'Card_WinryRockbell.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (303, 'Olivier Mira Armstrong', 27, 'Card_OlivierMiraArmstrong.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (304, 'Izumi Curtis', 27, 'Card_IzumiCurtis.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (305, 'Riza Hawkeye', 27, 'Card_RizaHawkeye.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (306, 'Yuzu Aihara', 122, 'Card_YuzuAihara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (307, 'Mei Aihara', 122, 'Card_MeiAihara.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (308, 'Rui Tachibana', 123, 'Card_RuiTachibana.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (309, 'Hina Tachibana', 123, 'Card_HinaTachibana.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (310, 'Narberal Gamma', 83, 'Card_NarberalGamma.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (311, 'Solution Epsilon', 83, 'Card_SolutionEpsilon.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (312, 'Milim Nava', 50, 'Card_MilimNava.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (313, 'Shuna', 50, 'Card_Shuna.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (314, 'Shion', 50, 'Card_Shion.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (315, 'Motoko Kusanagi', 124, 'Card_MotokoKusanagi.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (316, 'Suzune Horikita', 126, 'Card_SuzuneHorikita.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (317, 'Kikyo Kushida', 126, 'Card_KikyoKushida.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (318, 'Honami Ichinose', 126, 'Card_HonamiIchinose.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (319, 'Kei Karuizawa', 126, 'Card_KeiKaruizawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (320, 'Mamimi Samejima', 127, 'Card_MamimiSamejima.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (321, 'Haruko Haruhara', 127, 'Card_HarukoHaruhara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (322, 'Hidomi Hibajiri', 127, 'Card_HidomiHibajiri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (323, 'Kana Koumoto', 127, 'Card_KanaKoumoto.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (324, 'Julia Jinyu', 127, 'Card_JuliaJinyu.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (325, 'Hinae Hibajiri', 127, 'Card_HinaeHibajiri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (326, 'Yuria Harudera', 82, 'Card_YuriaHarudera.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (327, 'Ai Hayasaka', 3, 'Card_AiHayasaka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (328, 'Miko Iino', 3, 'Card_MikoIino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (329, 'Mugino Shizuri', 44, 'Card_MuginoShizuri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (330, 'Hitagi Senjougahara', 71, 'Card_HitagiSenjougahara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (331, 'Akatsuki', 128, 'Card_Akatsuki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (332, 'Henrietta', 128, 'Card_Henrietta.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (333, 'Marielle', 128, 'Card_Marielle.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (334, 'Fine Forte', 92, 'Card_FineForte.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (335, 'Prax Conrad', 92, 'Card_PraxConrad.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (336, 'Shouko Nishimiya', 129, 'Card_ShoukoNishimiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (337, 'Yuzuru Nishimiya', 129, 'Card_YuzuruNishimiya.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (338, 'Naoka Ueno', 129, 'Card_NaokaUeno.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (339, 'Rei Hino', 125, 'Card_ReiHino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (340, 'Makoto Kino', 125, 'Card_MakotoKino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (341, 'Usagi Tsukino', 125, 'Card_UsagiTsukino.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (342, 'Ami Mizuno', 125, 'Card_AmiMizuno.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (343, 'Minako Aino', 125, 'Card_MinakoAino.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (344, 'Shinobu Kochou', 55, 'Card_ShinobuKochou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (345, 'Kanao Tsuyuri', 55, 'Card_KanaoTsuyuri.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (346, 'Mitsuri Kanroji', 55, 'Card_MitsuriKanroji.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (347, 'Sayu Ogiwara', 130, 'Card_SayuOgiwara.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (348, 'Airi Gotou', 130, 'Card_AiriGotou.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (349, 'Yuzuha Mishima', 130, 'Card_YuzuhaMishima.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (350, 'Asami Yuuki', 130, 'Card_AsamiYuuki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (351, 'Kei Shirogane', 3, 'Card_KeiShirogane.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (352, 'Tohru Honda', 131, 'Card_TohruHonda.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (353, 'Azusa Aizawa', 132, 'Card_AzusaAizawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (354, 'Tornado/Tatsumaki', 133, 'Card_TornadoTatsumaki.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (355, 'Rikka Takarada', 134, 'Card_RikkaTakarada.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (356, 'Aisha Clanclan', 135, 'Card_AishaClanclan.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (357, 'Melfina', 135, 'Card_Melfina.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (358, 'Suzuka', 135, 'Card_Suzuka.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (359, 'Hilda', 135, 'Card_Hilda.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (360, 'Elizabeth Liones', 38, 'Card_ElizabethLiones.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (361, 'Diane', 38, 'Card_Diane.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (362, 'Merlin', 38, 'Card_Merlin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (363, 'Lucifer', 136, 'Card_Lucifer.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (364, 'Belial', 136, 'Card_Belial.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (365, 'Asmodeus', 136, 'Card_Asmodeus.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (366, 'Kimura no Tsuma', 137, 'Card_KimuranoTsuma.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (367, 'Charlotte Hazelrink', 138, 'Card_CharlotteHazelrink.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (368, 'Sylvia Van Hossen', 138, 'Card_SylviaVanHossen.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (369, 'Seika Hojoin', 138, 'Card_SeikaHojoin.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (370, 'Georgie Saikawa', 48, 'Card_GeorgieSaikawa.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (371, 'Sasakibe', 48, 'Card_Sasakibe.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (372, 'Kobayashi-san', 48, 'Card_Kobayashi-san.webp')
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (373, 'Shirley Fenette', 139, 'Card_ShirleyFenette.webp');
INSERT INTO cards (cid, cname, ctid, cimage) VALUES (374, 'Kallen Kozuki', 139, 'Card_KallenKozuki.webp');
