[package]
name = "rust"
version = "0.1.0"
authors = ["Nis5l <kirchler123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10.6", features = ["env", "toml", "json"] }
validator = { version = "0.14", features = ["derive"] }
rocketjson = { path = "C:/Users/kirch/OneDrive/Dokumente/rocket-json/core" }
regex = "1.5.4"
mysql = "21.0.1"
bcrypt = "0.10.1"
