INSERT INTO cardtypes (ctid, ctname) VALUES (1, 'Re:Zero');
INSERT INTO cardtypes (ctid, ctname) VALUES (2, 'DARLING in the FRANXX');
INSERT INTO cardtypes (ctid, ctname) VALUES (3, 'KAGUYA-SAMA: LOVE IS WAR');
INSERT INTO cardtypes (ctid, ctname) VALUES (4, 'KonoSuba');
INSERT INTO cardtypes (ctid, ctname) VALUES (5, 'Akame ga Kill!');
INSERT INTO cardtypes (ctid, ctname) VALUES (6, 'Attack on Titan');
INSERT INTO cardtypes (ctid, ctname) VALUES (7, 'Fairy Tail');
INSERT INTO cardtypes (ctid, ctname) VALUES (8, 'Boku wa Tomodachi ga Sukunai');
INSERT INTO cardtypes (ctid, ctname) VALUES (9, 'Neon Genesis Evangelion');
INSERT INTO cardtypes (ctid, ctname) VALUES (10, 'Kakegurui');
INSERT INTO cardtypes (ctid, ctname) VALUES (11, 'Bleach');
INSERT INTO cardtypes (ctid, ctname) VALUES (12, 'Noragami');
INSERT INTO cardtypes (ctid, ctname) VALUES (13, 'Food Wars!');
INSERT INTO cardtypes (ctid, ctname) VALUES (14, 'Naruto');
INSERT INTO cardtypes (ctid, ctname) VALUES (15, 'My Hero Academia');
INSERT INTO cardtypes (ctid, ctname) VALUES (16, 'Heavens Lost Property');
INSERT INTO cardtypes (ctid, ctname) VALUES (17, 'Sakurasou no Pet na Kanojo');
INSERT INTO cardtypes (ctid, ctname) VALUES (18, 'Plastic Memories');
INSERT INTO cardtypes (ctid, ctname) VALUES (19, 'Angel Beats!');
INSERT INTO cardtypes (ctid, ctname) VALUES (20, 'Nisekoi');
INSERT INTO cardtypes (ctid, ctname) VALUES (21, 'One Piece');
INSERT INTO cardtypes (ctid, ctname) VALUES (22, 'Date a Live');
INSERT INTO cardtypes (ctid, ctname) VALUES (23, 'Rosario + Vampire');
INSERT INTO cardtypes (ctid, ctname) VALUES (24, 'Trinity Seven');
INSERT INTO cardtypes (ctid, ctname) VALUES (25, 'Dr. Stone');
INSERT INTO cardtypes (ctid, ctname) VALUES (26, 'Sword Art Online');
INSERT INTO cardtypes (ctid, ctname) VALUES (27, 'Fullmetal Alchemist');
INSERT INTO cardtypes (ctid, ctname) VALUES (28, 'The Testament of Sister New Devil');
INSERT INTO cardtypes (ctid, ctname) VALUES (29, 'Kuroko no Basuke');
INSERT INTO cardtypes (ctid, ctname) VALUES (30, 'Highschool DxD');
INSERT INTO cardtypes (ctid, ctname) VALUES (31, 'Charlotte');
INSERT INTO cardtypes (ctid, ctname) VALUES (32, 'The Rising Of The Shield Hero');
INSERT INTO cardtypes (ctid, ctname) VALUES (33, 'Highscool of the Dead');
INSERT INTO cardtypes (ctid, ctname) VALUES (35, 'Dragon Ball');
INSERT INTO cardtypes (ctid, ctname) VALUES (36, 'Angels of Death');
INSERT INTO cardtypes (ctid, ctname) VALUES (37, 'Code Geass');
INSERT INTO cardtypes (ctid, ctname) VALUES (38, 'Seven deadly sins');
INSERT INTO cardtypes (ctid, ctname) VALUES (39, 'Daily Life With A Monster Girl');
INSERT INTO cardtypes (ctid, ctname) VALUES (40, 'Assassination Classroom');
INSERT INTO cardtypes (ctid, ctname) VALUES (41, 'Your Lie in April');
INSERT INTO cardtypes (ctid, ctname) VALUES (42, 'Undefeated Bahamut Chronicle');
INSERT INTO cardtypes (ctid, ctname) VALUES (43, 'Initial D');
INSERT INTO cardtypes (ctid, ctname) VALUES (44, 'A Certain Scientific Railgun');
INSERT INTO cardtypes (ctid, ctname) VALUES (45, 'A Certain Magical Index');
INSERT INTO cardtypes (ctid, ctname) VALUES (46, 'The Asterisk War');
INSERT INTO cardtypes (ctid, ctname) VALUES (47, 'Tokyo Ghoul');
INSERT INTO cardtypes (ctid, ctname) VALUES (48, 'Miss Kobayashis Dragon Maid');
INSERT INTO cardtypes (ctid, ctname) VALUES (49, 'Guilty Crown');
INSERT INTO cardtypes (ctid, ctname) VALUES (50, 'That Time I Got Reincarnated as a Slime');
INSERT INTO cardtypes (ctid, ctname) VALUES (51, 'Rent-A-Girlfriend');
INSERT INTO cardtypes (ctid, ctname) VALUES (52, 'Fate');
INSERT INTO cardtypes (ctid, ctname) VALUES (53, 'Death Note');
INSERT INTO cardtypes (ctid, ctname) VALUES (54, 'Owari no Seraph');
INSERT INTO cardtypes (ctid, ctname) VALUES (55, 'Demon Slayer');
INSERT INTO cardtypes (ctid, ctname) VALUES (56, 'Violet Evergarden');
INSERT INTO cardtypes (ctid, ctname) VALUES (57, 'Kuma Kuma Kuma Bear');
INSERT INTO cardtypes (ctid, ctname) VALUES (58, 'Sabagebu!');
INSERT INTO cardtypes (ctid, ctname) VALUES (59, 'DanMachi');
INSERT INTO cardtypes (ctid, ctname) VALUES (60, 'Bunny Girl Senpai');
INSERT INTO cardtypes (ctid, ctname) VALUES (61, 'Tonikaku Kawaii');
INSERT INTO cardtypes (ctid, ctname) VALUES (62, 'Fire Force');
INSERT INTO cardtypes (ctid, ctname) VALUES (63, 'The Irregular at Magic High School');
INSERT INTO cardtypes (ctid, ctname) VALUES (64, 'Strike The Blood');
INSERT INTO cardtypes (ctid, ctname) VALUES (65, 'Black Clover');
INSERT INTO cardtypes (ctid, ctname) VALUES (66, 'Majo No Tabitabi');
INSERT INTO cardtypes (ctid, ctname) VALUES (67, 'Uzaki-Chan Wants To Hang Out!');
INSERT INTO cardtypes (ctid, ctname) VALUES (68, 'The Quintessential Quintuplets');
INSERT INTO cardtypes (ctid, ctname) VALUES (69, 'Horimiya');
INSERT INTO cardtypes (ctid, ctname) VALUES (70, 'Show By Rock!!');
INSERT INTO cardtypes (ctid, ctname) VALUES (71, 'Monogatari Series');
INSERT INTO cardtypes (ctid, ctname) VALUES (72, 'Kill la Kill');
INSERT INTO cardtypes (ctid, ctname) VALUES (73, 'Promare');
INSERT INTO cardtypes (ctid, ctname) VALUES (74, 'Land of the Lustrous');
INSERT INTO cardtypes (ctid, ctname) VALUES (75, 'Akudama Drive');
INSERT INTO cardtypes (ctid, ctname) VALUES (76, 'Hellsing Ultimate');
INSERT INTO cardtypes (ctid, ctname) VALUES (77, 'Kara no Kyoukai');
INSERT INTO cardtypes (ctid, ctname) VALUES (78, 'No Game No Life');
INSERT INTO cardtypes (ctid, ctname) VALUES (79, 'Mushoku Tensei');
INSERT INTO cardtypes (ctid, ctname) VALUES (80, 'JoJos Bizarre Adventure');
INSERT INTO cardtypes (ctid, ctname) VALUES (81, 'Yuunas Haunted Hot Springs');
INSERT INTO cardtypes (ctid, ctname) VALUES (82, 'The Fruit of Grisaia');
INSERT INTO cardtypes (ctid, ctname) VALUES (83, 'Overlord');
INSERT INTO cardtypes (ctid, ctname) VALUES (84, 'Watamote')
INSERT INTO cardtypes (ctid, ctname) VALUES (85, 'How Not to Summon a Demon Lord');
INSERT INTO cardtypes (ctid, ctname) VALUES (86, 'Redo of Healer');
INSERT INTO cardtypes (ctid, ctname) VALUES (87, 'Love, Chunibyo & Other Delusions!');
INSERT INTO cardtypes (ctid, ctname) VALUES (88, 'Another');
INSERT INTO cardtypes (ctid, ctname) VALUES (89, 'Oreshura');
INSERT INTO cardtypes (ctid, ctname) VALUES (90, 'Goblin Slayer')
INSERT INTO cardtypes (ctid, ctname) VALUES (91, 'Uma Musume')
INSERT INTO cardtypes (ctid, ctname) VALUES (92, 'Back Arrow');
INSERT INTO cardtypes (ctid, ctname) VALUES (93, 'Wonder Egg Priority');
INSERT INTO cardtypes (ctid, ctname) VALUES (94, 'Spice and Wolf');
INSERT INTO cardtypes (ctid, ctname) VALUES (95, 'Hokuto no Ken')
INSERT INTO cardtypes (ctid, ctname) VALUES (96, 'Mirai Nikki');
INSERT INTO cardtypes (ctid, ctname) VALUES (97, 'Darker than Black');
INSERT INTO cardtypes (ctid, ctname) VALUES (98, 'Kabaneri of the Iron Fortress');
INSERT INTO cardtypes (ctid, ctname) VALUES (99, 'Kyokou Suiri');
INSERT INTO cardtypes (ctid, ctname) VALUES (100, 'Welcome to the N.H.K.');
INSERT INTO cardtypes (ctid, ctname) VALUES (101, 'Shimoneta');
INSERT INTO cardtypes (ctid, ctname) VALUES (102, 'Mysterious Girlfriend X');
INSERT INTO cardtypes (ctid, ctname) VALUES (103, 'Jormungand');
INSERT INTO cardtypes (ctid, ctname) VALUES (104, 'How Heavy are the Dumbbells You Lift?');
INSERT INTO cardtypes (ctid, ctname) VALUES (105, 'Bungo Stray Dogs')
INSERT INTO cardtypes (ctid, ctname) VALUES (106, 'Hanasaku Iroha');
INSERT INTO cardtypes (ctid, ctname) VALUES (107, 'Problem Children are Coming from Another World Arent They?');
INSERT INTO cardtypes (ctid, ctname) VALUES (108, 'Space Dandy');
INSERT INTO cardtypes (ctid, ctname) VALUES (109, 'Higurashi')
INSERT INTO cardtypes (ctid, ctname) VALUES (110, 'Rokka: Braves of the Six Flowers');
INSERT INTO cardtypes (ctid, ctname) VALUES (111, 'Bofuri');
INSERT INTO cardtypes (ctid, ctname) VALUES (112, 'Arcade Gamer Fubuki');
INSERT INTO cardtypes (ctid, ctname) VALUES (113, 'WorldEnd');
INSERT INTO cardtypes (ctid, ctname) VALUES (114, 'Claymore');
INSERT INTO cardtypes (ctid, ctname) VALUES (115, 'Tenga Toppa Gurren Lagann');
INSERT INTO cardtypes (ctid, ctname) VALUES (116, 'Arifureta');
INSERT INTO cardtypes (ctid, ctname) VALUES (117, 'Cowboy Bebop');
INSERT INTO cardtypes (ctid, ctname) VALUES (118, 'Cautious Hero');
INSERT INTO cardtypes (ctid, ctname) VALUES (119, 'Serial Experiments Lain');
INSERT INTO cardtypes (ctid, ctname) VALUES (120, 'Sankarea');
INSERT INTO cardtypes (ctid, ctname) VALUES (121, 'Magical Sempai');
INSERT INTO cardtypes (ctid, ctname) VALUES (122, 'Citrus');
INSERT INTO cardtypes (ctid, ctname) VALUES (123, 'Domestic Girlfriend')
INSERT INTO cardtypes (ctid, ctname) VALUES (124, 'Ghost in the Shell');
INSERT INTO cardtypes (ctid, ctname) VALUES (125, 'Sailor Moon');
INSERT INTO cardtypes (ctid, ctname) VALUES (126, 'Classroom of the Elite');
INSERT INTO cardtypes (ctid, ctname) VALUES (127, 'Fooly Cooly');
INSERT INTO cardtypes (ctid, ctname) VALUES (128, 'Log Horizon');
INSERT INTO cardtypes (ctid, ctname) VALUES (129, 'A Silent Voice');
INSERT INTO cardtypes (ctid, ctname) VALUES (130, 'Higehiro');
INSERT INTO cardtypes (ctid, ctname) VALUES (131, 'Fruits Basket');
INSERT INTO cardtypes (ctid, ctname) VALUES (132, 'Ive Been Killing Slimes for 300 Years and Maxed Out My Level');
INSERT INTO cardtypes (ctid, ctname) VALUES (133, 'One Punch Man')
INSERT INTO cardtypes (ctid, ctname) VALUES (134, 'SSSS Gridman');
INSERT INTO cardtypes (ctid, ctname) VALUES (135, 'Outlaw Star');
INSERT INTO cardtypes (ctid, ctname) VALUES (136, 'Sins: The Seven Deadly Sins');
INSERT INTO cardtypes (ctid, ctname) VALUES (137, 'Azumanga Daioh');
INSERT INTO cardtypes (ctid, ctname) VALUES (138, 'Princess Lover!');
INSERT INTO cardtypes (ctid, ctname) VALUES (139, 'Code Geass');
INSERT INTO cardtypes (ctid, ctname) VALUES (140, 'Ijiranaide, Nagatoro-san');
INSERT INTO cardtypes (ctid, ctname) VALUES (141, 'Black Lagoon');
INSERT INTO cardtypes (ctid, ctname) VALUES (142, 'Komi Cant Comunicate');
INSERT INTO cardtypes (ctid, ctname) VALUES (143, 'Cowboy Bebop');
INSERT INTO cardtypes (ctid, ctname) VALUES (144, 'Infinite Stratos');
INSERT INTO cardtypes (ctid, ctname) VALUES (145, 'How a Realist Hero Rebuilt the Kingdom');
INSERT INTO cardtypes (ctid, ctname) VALUES (146, 'Cat Planet Cuties');
INSERT INTO cardtypes (ctid, ctname) VALUES (147, 'Why the Hell are You Here, Teacher!?');
INSERT INTO cardtypes (ctid, ctname) VALUES (148, 'Kandagawa Jet Girls');
INSERT INTO cardtypes (ctid, ctname) VALUES (149, 'KEIJO!!!!!!!!');
INSERT INTO cardtypes (ctid, ctname) VALUES (150, 'Ao-chan Cant Study');
INSERT INTO cardtypes (ctid, ctname) VALUES (151, 'To Love Ru');
