INSERT IGNORE INTO cards (cid, cname, ctid, cimage) VALUES
(1, 'Rem', 1, 'Card_Rem.webp'),
(2, 'ZeroTwo', 2, 'Card_ZeroTwo.webp'),
(3, 'Chika', 3, 'Card_Chika.webp'),
(4, 'Megumin', 4, 'Card_Megumin.webp'),
(5, 'Akame', 5, 'Card_Akame.webp'),
(6, 'Annie Leonhardt', 6, 'Card_AnnieLeonhardt.webp'),
(7, 'Lucy Heartfilia', 7, 'Card_LucyHeartfilia.webp'),
(8, 'Ram', 1, 'Card_Ram.webp'),
(9, 'Kashiwazaki Sena', 8, 'Card_KashiwazakiSena.webp'),
(10, 'Ayanami Rei', 9, 'Card_AyanamiRei.webp'),
(11, 'Mary Saotome', 10, 'Card_MarySaotome.webp'),
(12, 'Rukia Kuchiki', 11, 'Card_RukiaKuchiki.webp'),
(13, 'Bishamonten', 12, 'Card_Bishamonten.webp'),
(14, 'Ikumi Mito', 13, 'Card_IkumiMito.webp'),
(15, 'Ino Yamanaka', 14, 'Card_InoYamanaka.webp'),
(16, 'Chelsea', 5, 'Card_Chelsea.webp'),
(17, 'Emilia', 1, 'Card_Emilia.webp'),
(18, 'Esdeath', 5, 'Card_Esdeath.webp'),
(19, 'Himiko Toga', 15, 'Card_HimikoToga.webp'),
(20, 'Jirou Kyouka', 15, 'Card_JirouKyouka.webp'),
(21, 'Ikaros', 16, 'Card_Ikaros.webp'),
(22, 'Shiina Mashiro', 17, 'Card_ShiinaMashiro.webp'),
(23, 'Isla', 18, 'Card_Isla.webp'),
(24, 'Kanade Tachibana', 19, 'Card_KanadeTachibana.webp'),
(25, 'Kirisaki Chitoge', 20, 'Card_KirisakiChitoge.webp'),
(26, 'Miss Valentine', 21, 'Card_MissValentine.webp'),
(27, 'Kurome', 5, 'Card_Kurome.webp'),
(28, 'Kurumi Tokisaki', 22, 'Card_KurumiTokisaki.webp'),
(29, 'Mizore', 23, 'Card_Mizore.webp'),
(30, 'Nami', 21, 'Card_Nami.webp'),
(31, 'Lieselotte Sherlock', 24, 'Card_LieselotteSherlock.webp'),
(32, 'Ruri', 25, 'Card_Ruri.webp'),
(33, 'Kirigaya Suguha', 26, 'Card_KirigayaSuguha.webp'),
(34, 'Lan Fan', 27, 'Card_LanFan.webp'),
(35, 'Leone', 5, 'Card_Leone.webp'),
(36, 'Mio Naruse', 28, 'Card_MioNaruse.webp'),
(37, 'Satsuki Momoi', 29, 'Card_SatsukiMomoi.webp'),
(38, 'Koneko Toujou', 30, 'Card_KonekoToujou.webp'),
(39, 'Erza Scarlet', 7, 'Card_ErzaScarlet.webp'),
(40, 'Nao Tomori', 31, 'Card_NaoTomori.webp'),
(41, 'Xenovia', 30, 'Card_Xenovia.webp'),
(42, 'Raphtalia', 32, 'Card_Raphtalia.webp'),
(43, 'Rei Miyamoto', 33, 'Card_ReiMiyamoto.webp'),
(44, 'Rindo Kobayashi', 13, 'Card_RindoKobayashi.webp'),
(45, 'Erina Nakiri', 13, 'Card_ErinaNakiri.webp'),
(46, 'Nakiri Alice', 13, 'Card_NakiriAlice.webp'),
(47, 'Temari', 14, 'Card_Temari.webp'),
(48, 'Tsunade', 14, 'Card_Tsunade.webp'),
(49, 'Jabami Yumeko', 10, 'Card_JabamiYumeko.webp'),
(50, 'Kirai Momobami', 10, 'Card_KiraiMomobami.webp'),
(51, 'Alice Zuberg', 26, 'Card_AliceZuberg.webp'),
(52, 'C18', 35, 'Card_C18.webp'),
(53, 'Astil Manuscript', 24, 'Card_AstilManuscript.webp'),
(54, 'Rachel Gardner', 36, 'Card_RachelGardner.webp'),
(55, 'Camie Utsumishi', 15, 'Card_CamieUtsumishi.webp'),
(56, 'C C', 37, 'Card_CC.webp'),
(57, 'Darkness', 4, 'Card_Darkness.webp'),
(58, 'Elaine', 38, 'Card_Elaine.webp'),
(59, 'Papi', 39, 'Card_Papi.webp'),
(60, 'Rachnera Arachnera', 39, 'Card_RachneraArachnera.webp'),
(61, 'Asia Argento', 30, 'Card_AsiaArgento.webp'),
(62, 'Irina Jelavic', 40, 'Card_IrinaJelavic.webp'),
(63, 'Boa Hancock', 21, 'Card_BoaHancock.webp'),
(64, 'Historia Reiss', 6, 'Card_HistoriaReiss.webp'),
(65, 'Hanabi Hyuga', 14, 'Card_HanabiHyuga.webp'),
(66, 'Kaori Miyazono', 41, 'Card_KaoriMiyazono.webp'),
(67, 'Kurumu Kurono', 23, 'Card_KurumuKurono.webp'),
(68, 'Lisesharte Atismata', 42, 'Card_LisesharteAtismata.webp'),
(69, 'Moka Akashiya', 23, 'Card_MokaAkashiya.webp'),
(70, 'Ririka Momobami', 10, 'Card_RirikaMomobami.webp'),
(71, 'Natsuki Mogi', 43, 'Card_NatsukiMogi.webp'),
(72, 'Mikasa Ackermann', 6, 'Card_MikasaAckermann.webp'),
(73, 'Aqua', 4, 'Card_Aqua.webp'),
(74, 'Shokuhou Misaki', 44, 'Card_ShokuhouMisaki.webp'),
(75, 'Mikoto Misaka', 44, 'Card_MikotoMisaka.webp'),
(76, 'Kanzaki Kaori', 45, 'Card_KanzakiKaori.webp'),
(77, 'Julis Riessfeld', 46, 'Card_JulisRiessfeld.webp'),
(78, 'Mine', 5, 'Card_Mine.webp'),
(79, 'Toudou Kirin', 46, 'Card_ToudouKirin.webp'),
(80, 'Claudia Enfield', 46, 'Card_ClaudiaEnfield.webp'),
(81, 'Sasamiya Saya', 46, 'Card_SasamiyaSaya.webp'),
(82, 'Toka Kirishima', 47, 'Card_TokaKirishima.webp'),
(83, 'Tohru', 48, 'Card_Tohru.webp'),
(84, 'Kanna Kamui', 48, 'Card_KannaKamui.webp'),
(85, 'Lucoa', 48, 'Card_Lucoa.webp'),
(86, 'Elma', 48, 'Card_Elma.webp'),
(87, 'Ichigo', 2, 'Card_Ichigo.webp'),
(88, 'Runa Yomozuki', 10, 'Card_RunaYomozuki.webp'),
(89, 'Yuriko Nishinotouin', 10, 'Card_YurikoNishinotouin.webp'),
(90, 'Yumemite Yumemi', 10, 'Card_YumemiteYumemi.webp'),
(91, 'Shizue Izawa', 50, 'Card_ShizueIzawa.webp'),
(92, 'Rias Gremory', 30, 'Card_RiasGremory.webp'),
(93, 'Hinata Hyuga', 14, 'Card_HinataHyuga.webp'),
(94, 'Asuna Yuuki', 26, 'Card_AsunaYuuki.webp'),
(95, 'Chizuru Mizuhara', 51, 'Card_ChizuruMizuhara.webp'),
(96, 'Ruka Sarashina', 51, 'Card_RukaSarashina.webp'),
(97, 'Mami Nanami', 51, 'Card_MamiNanami.webp'),
(98, 'Sumi Sakurasawa', 51, 'Card_SumiSakurasawa.webp'),
(99, 'Rin Tohsaka', 52, 'Card_RinTohsaka.webp'),
(100, 'Misa Amane', 53, 'Card_MisaAmane.webp'),
(101, 'Shinoa Hiragi', 54, 'Card_ShinoaHiragi.webp'),
(102, 'Nezuko Kamado', 55, 'Card_NezukoKamado.webp'),
(103, 'Saber', 52, 'Card_ArtoriaPendragon.webp'),
(104, 'Violet Evergarden', 56, 'Card_VioletEvergarden.webp'),
(105, 'Yuna', 57, 'Card_Yuna.webp'),
(106, 'Momoka Sonokawa', 58, 'Card_MomokaSonokawa.webp'),
(107, 'Miou Ootori', 58, 'Card_MiouOotori.webp'),
(108, 'Maya Kyodo', 58, 'Card_MayaKyodo.webp'),
(109, 'Urara Kasugano', 58, 'Card_UraraKasugano.webp'),
(110, 'Yui', 19, 'Card_Yui.webp'),
(111, 'Yuri Nakamura', 19, 'Card_YuriNakamura.webp'),
(112, 'Eri Shiina', 19, 'Card_EriShiina.webp'),
(113, 'Hestia', 59, 'Card_Hestia.webp'),
(114, 'Yamato Mikoto', 59, 'Card_YamatoMikoto.webp'),
(115, 'Sanjouno Haruhime', 59, 'Card_SanjounoHaruhime.webp'),
(116, 'Ais Wallenstein', 59, 'Card_AisWallenstein.webp'),
(117, 'Syr Flova', 59, 'Card_SyrFlova.webp'),
(118, 'Ryuu Lion', 59, 'Card_RyuuLion.webp'),
(119, 'Eina Tulle', 59, 'Card_EinaTulle.webp'),
(120, 'Kaguya Shinomiya', 3, 'Card_KaguyaShinomiya.webp'),
(121, 'Mai Sakurajima', 60, 'Card_MaiSakurajima.webp'),
(122, 'Kaname Arisugawa', 61, 'Card_KanameArisugawa.webp'),
(123, 'Aya Arisugawa', 61, 'Card_AyaArisugawa.webp'),
(124, 'Tsukasa Tsukuyomi', 61, 'Card_TsukasaTsukuyomi.webp'),
(125, 'Maki Oze', 62, 'Card_MakiOze.webp'),
(126, 'Noel Niihashi', 11, 'Card_NoelNiihashi.webp'),
(127, 'Shiba Miyuki', 63, 'Card_ShibaMiyuki.webp'),
(128, 'Sayaka Kirasaka', 64, 'Card_SayakaKirasaka.webp'),
(129, 'Vanessa Anoteca', 65, 'Card_VanessaAnoteca.webp'),
(130, 'Elaina', 66, 'Card_Elaina.webp'),
(131, 'Echidna', 1, 'Card_Echidna.webp'),
(132, 'Noelle Silva', 65, 'Card_NoelleSilva.webp'),
(133, 'Charlotte Roselei', 65, 'Card_CharlotteRoselei.webp'),
(134, 'Nero', 65, 'Card_Nero.webp'),
(135, 'Mimosa Vermillion', 65, 'Card_MimosaVermillion.webp'),
(136, 'Hana Uzaki', 67, 'Card_HanaUzaki.webp'),
(137, 'Ichika Nakano', 68, 'Card_IchikaNakano.webp'),
(138, 'Nino Nakano', 68, 'Card_NinoNakano.webp'),
(139, 'Miku Nakano', 68, 'Card_MikuNakano.webp'),
(140, 'Yotsuba Nakano', 68, 'Card_YotsubaNakano.webp'),
(141, 'Itsuki Nakano', 68, 'Card_ItsukiNakano.webp'),
(142, 'Hori Kyouko', 69, 'Card_HoriKyouko.webp'),
(143, 'Cyan', 70, 'Card_Cyan.webp'),
(144, 'Kohaku', 25, 'Card_Kohaku.webp'),
(145, 'Shinobu Oshino', 71, 'Card_ShinobuOshino.webp'),
(146, 'Suruga Kanbaru', 71, 'Card_SurugaKanbaru.webp'),
(147, 'Tsubasa Hanekawa', 71, 'Card_TsubasaHanekawa.webp'),
(148, 'Ougi Oshino', 71, 'Card_OugiOshino.webp'),
(149, 'Izuko Gaen', 71, 'Card_IzukoGaen.webp'),
(150, 'Ryuko Matoi', 72, 'Card_RyukoMatoi.webp'),
(151, 'Satsuki Kiryuin', 72, 'Card_SatsukiKiryuin.webp'),
(152, 'Nui Harime', 72, 'Card_NuiHarime.webp'),
(153, 'Mako Mankanshoku', 72, 'Card_MakoMankanshoku.webp'),
(154, 'Nonon Jakuzure', 72, 'Card_NononJakuzure.webp'),
(155, 'Kokoro', 2, 'Card_Kokoro.webp'),
(156, 'Miku', 2, 'Card_Miku.webp'),
(157, 'Ikuno', 2, 'Card_Ikuno.webp'),
(158, '001', 2, 'Card_001.webp'),
(159, 'Aina Ardebit', 73, 'Card_AinaArdebit.webp'),
(160, 'Phosphophyllite', 74, 'Card_Phosphophyllite.webp'),
(161, 'Cinnabar', 74, 'Card_Cinnabar.webp'),
(162, 'Diamond', 74, 'Card_Diamond.webp'),
(163, 'Swindler', 75, 'Card_Swindler.webp'),
(164, 'Seras Victoria', 76, 'Card_SerasVictoria.webp'),
(165, 'Shiki Ryougi', 77, 'Card_ShikiRyougi.webp'),
(166, 'Asuka Langley Sohryu', 9, 'Card_AsukaLangleySohryu.webp'),
(167, 'Misato Katsuragi', 9, 'Card_MisatoKatsuragi.webp'),
(168, 'Stephanie Dola', 78, 'Card_StephanieDola.webp'),
(169, 'Jibril', 78, 'Card_Jibril.webp'),
(170, 'Ochako Uraraka', 15, 'Card_OchakoUraraka.webp'),
(171, 'Tsuyu Asui', 15, 'Card_TsuyuAsui.webp'),
(172, 'Momo Yaoyorozu', 15, 'Card_MomoYaoyorozu.webp'),
(173, 'Nejire Hado', 15, 'Card_NejireHado.webp'),
(174, 'Mei Hatsume', 15, 'Card_MeiHatsume.webp'),
(175, 'Roxy Migurdia', 79, 'Card_RoxyMigurdia.webp'),
(176, 'Eris Boreas Greyrat', 79, 'Card_ErisBoreasGreyrat.webp'),
(177, 'Ghislaine Dedoldia', 79, 'Card_GhislaineDedoldia.webp'),
(178, 'Sylphiette', 79, 'Card_Sylphiette.webp'),
(179, 'Robert E O Speedwagon', 80, 'Card_RobertEOSpeedwagon.webp'),
(180, 'Sakura Matou', 52, 'Card_SakuraMatou.webp'),
(181, 'Yuuna Yunohana', 81, 'Card_YuunaYunohana.webp'),
(182, 'Amane Suou', 82, 'Card_AmaneSuou.webp'),
(183, 'Yumiko Sakaki', 82, 'Card_YumikoSakaki.webp'),
(184, 'Michiru Matsushima', 82, 'Card_MichiruMatsushima.webp'),
(185, 'Sachi Komine', 82, 'Card_SachiKomine.webp'),
(186, 'Makina Irisu', 82, 'Card_MakinaIrisu.webp'),
(187, 'Kazuki Kazami', 82, 'Card_KazukiKazami.webp'),
(188, 'Akeno Himejima', 30, 'Card_AkenoHimejima.webp'),
(189, 'Ravel Phoenix', 30, 'Card_RavelPhoenix.webp'),
(190, 'Albedo', 83, 'Card_Albedo.webp'),
(191, 'Lisa Lisa', 80, 'Card_LisaLisa.webp'),
(192, 'Trish Una', 80, 'Card_TrishUna.webp'),
(193, 'Yukako Yamagishi', 80, 'Card_YukakoYamagishi.webp'),
(194, 'Yoruichi Shihoin', 11, 'Card_YoruichiShihoin.webp'),
(195, 'Nemu Kurotsuchi', 11, 'Card_NemuKurotsuchi.webp'),
(196, 'Sode no Shirayuki', 11, 'Card_SodenoShirayuki.webp'),
(197, 'Nelliel Tu Odelschwanck', 11, 'Card_NellielTuOdelschwanck.webp'),
(198, 'Tier Harribel', 11, 'Card_TierHarribel.webp'),
(199, 'Cyan Sung-Sun', 11, 'Card_CyanSung-Sun.webp'),
(200, 'Lisa Yadomaru', 11, 'Card_LisaYadomaru.webp'),
(201, 'Hiyori Sarugaki', 11, 'Card_HiyoriSarugaki.webp'),
(202, 'Charmy Pappitson', 65, 'Card_CharmyPappitson.webp'),
(203, 'Vanica Zogratis', 65, 'Card_VanicaZogratis.webp'),
(204, 'Fana', 65, 'Card_Fana.webp'),
(205, 'Sister Lily', 65, 'Card_SisterLily.webp'),
(206, 'Dorothy Unsworth', 65, 'Card_DorothyUnsworth.webp'),
(207, 'Sol Marron', 65, 'Card_SolMarron.webp'),
(208, 'Nico Robin', 21, 'Card_NicoRobin.webp'),
(209, 'Shirahoshi', 21, 'Card_Shirahoshi.webp'),
(210, 'Nefertari Vivi', 21, 'Card_NefeltariVivi.webp'),
(211, 'Carrot', 21, 'Card_Carrot.webp'),
(212, 'Charlotte Pudding', 21, 'Card_CharlottePudding.webp'),
(213, 'Kozuki Hiyori', 21, 'Card_KozukiHiyori.webp'),
(214, 'Marguerite', 21, 'Card_Marguerite.webp'),
(215, 'Tomoko Kuroki', 84, 'Card_TomokoKuroki.webp'),
(216, 'Yuu Naruse', 84, 'Card_YuuNaruse.webp'),
(217, 'Rem Galleu', 85, 'Card_RemGalleu.webp'),
(218, 'Setsuna', 86, 'Card_Setsuna.webp'),
(219, 'Rikka Takanashi', 87, 'Card_RikkaTakanashi.webp'),
(220, 'Satone Shichimiya', 87, 'Card_SatoneShichimiya.webp'),
(221, 'Kumin Tsuyuri', 87, 'Card_KuminTsuyuri.webp'),
(222, 'Yoshino Himekawa', 22, 'Card_YoshinoHimekawa.webp'),
(223, 'Itsuka Kotori', 22, 'Card_ItsukaKotori.webp'),
(224, 'Kaguya Yamai', 22, 'Card_KaguyaYamai.webp'),
(225, 'Yamai Kazamachi', 22, 'Card_YamaiKazamachi.webp'),
(226, 'Tohka Yatogami', 22, 'Card_TohkaYatogami.webp'),
(227, 'Mei Misaki', 88, 'Card_MeiMisaki.webp'),
(228, 'Himeka Akishino', 89, 'Card_HimekaAkishino.webp'),
(229, 'Chiwa Harusaki', 89, 'Card_ChiwaHarusaki.webp'),
(230, 'Kaede Azusagawa', 60, 'Card_KaedeAzusagawa.webp'),
(231, 'Onna Shinkan', 90, 'Card_OnnaShinkan.webp'),
(232, 'Erufu', 90, 'Card_Erufu.webp'),
(233, 'Shalltear Bloodfallen', 83, 'Card_ShalltearBloodfallen.webp'),
(234, 'Reimi Sugimoto', 80, 'Card_ReimiSugimoto.webp'),
(235, 'Erina Pendleton', 80, 'Card_ErinaPendleton.webp'),
(236, 'Suzie Q', 80, 'Card_SuzieQ.webp'),
(237, 'Elsha Lean', 92, 'Card_ElshaLean.webp'),
(238, 'Atlee Ariel', 92, 'Card_AtleeAriel.webp'),
(239, 'Ren Sin', 92, 'Card_RenSin.webp'),
(240, 'Ai Ohto', 93, 'Card_AiOhto.webp'),
(241, 'Holo', 94, 'Card_Holo.webp'),
(242, 'Yuria', 95, 'Card_Yuria.webp'),
(243, 'Tou', 95, 'Card_Tou.webp'),
(244, 'Mamiya', 95, 'Card_Mamiya.webp'),
(245, 'Ilulu', 48, 'Card_Ilulu.webp'),
(246, 'Yuno Gasai', 96, 'Card_YunoGasai.webp'),
(247, 'Minene Uryuu', 96, 'Card_MineneUryuu.webp'),
(248, 'Yin', 97, 'Card_Yin.webp'),
(249, 'Amber', 97, 'Card_Amber.webp'),
(250, 'Misaki Kirihara', 97, 'Card_MisakiKirihara.webp'),
(251, 'Mumei', 98, 'Card_Mumei.webp'),
(252, 'Kotoko Iwanaga', 99, 'Card_KotokoIwanaga.webp'),
(253, 'Saki Yumihara', 99, 'Card_SakiYumihara.webp'),
(254, 'Misaki Nakahara', 100, 'Card_MisakiNakahara.webp'),
(255, 'Ayame Kajou', 101, 'Card_AyameKajou.webp'),
(256, 'Anna Nishikinomiya', 101, 'Card_AnnaNishikinomiya.webp'),
(257, 'Mikoto Urabe', 102, 'Card_MikotoUrabe.webp'),
(258, 'Koko Hekmatyar', 103, 'Card_KokoHekmatyar.webp'),
(259, 'Sakura Hibiki', 104, 'Card_SakuraHibiki.webp'),
(260, 'Soryuin Akemi', 104, 'Card_SoryuinAkemi.webp'),
(261, 'Zina Void', 104, 'Card_ZinaVoid.webp'),
(262, 'Uehara Ayaka', 104, 'Card_UeharaAyaka.webp'),
(263, 'Akiko Yosano', 105, 'Card_AkikoYosano.webp'),
(264, 'Kyoko Izumi', 105, 'Card_KyokoIzumi.webp'),
(265, 'Naomi Tanizaki', 105, 'Card_NaomiTanizaki.webp'),
(266, 'Ichiyo Higuchi', 105, 'Card_IchiyoHiguchi.webp'),
(267, 'Clementine', 83, 'Card_Clementine.webp'),
(268, 'Special Week', 91, 'Card_SpecialWeek.webp'),
(269, 'Vodka', 91, 'Card_Vodka.webp'),
(270, 'Silence Suzuka', 91, 'Card_SilenceSuzuka.webp'),
(271, 'Tokai Teio', 91, 'Card_TokaiTeio.webp'),
(272, 'Gold Ship', 91, 'Card_GoldShip.webp'),
(273, 'Daiwa Scarlet', 91, 'Card_DaiwaScarlet.webp'),
(274, 'Ohana Matsumae', 106, 'Card_OhanaMatsumae.webp'),
(275, 'Black Rabbit', 107, 'Card_BlackRabbit.webp'),
(276, 'Honey', 108, 'Card_Honey.webp'),
(277, 'Rena Ryuuguu', 109, 'Card_RenaRyuuguu.webp'),
(278, 'Mion Sonozaki', 109, 'Card_MionSonozaki.webp'),
(279, 'Shion Sonozaki', 109, 'Card_ShionSonozaki.webp'),
(280, 'Satoko Houjou', 109, 'Card_SatokoHoujou.webp'),
(281, 'Rika Furude', 109, 'Card_RikaFurude.webp'),
(282, 'Inori Yuzuriha', 49, 'Card_InoriYuzuriha.webp'),
(283, 'Nashetania Loei Piena Augustra', 110, 'Card_NashetaniaLoeiPienaAugustra.webp'),
(284, 'Flamie Speeddraw', 110, 'Card_FlamieSpeeddraw.webp'),
(285, 'Maple', 111, 'Card_Maple.webp'),
(286, 'Fubuki Sakuragasaki', 112, 'Card_FubukiSakuragasaki.webp'),
(287, 'Chtholly Nota Seniorious', 113, 'Card_ChthollyNotaSeniorious.webp'),
(288, 'Clare', 114, 'Card_Clare.webp'),
(289, 'Yoko Littner', 115, 'Card_YokoLittner.webp'),
(290, 'Yue', 116, 'Card_Yue.webp'),
(291, 'Shea Haulia', 116, 'Card_SheaHaulia.webp'),
(292, 'Faye Valentine', 117, 'Card_FayeValentine.webp'),
(293, 'Judy', 117, 'Card_Judy.webp'),
(294, 'Ristarte', 118, 'Card_Ristarte.webp'),
(295, 'Perona', 21, 'Card_Perona.webp'),
(296, 'Lain', 119, 'Card_Lain.webp'),
(297, 'Rea Sanka', 120, 'Card_ReaSanka.webp'),
(298, 'Sempai', 121, 'Card_Sempai.webp'),
(299, 'Saki', 121, 'Card_Saki.webp'),
(300, 'Madara', 121, 'Card_Madara.webp'),
(301, 'Bulma', 35, 'Card_Bluma.webp'),
(302, 'Winry Rockbell', 27, 'Card_WinryRockbell.webp'),
(303, 'Olivier Mira Armstrong', 27, 'Card_OlivierMiraArmstrong.webp'),
(304, 'Izumi Curtis', 27, 'Card_IzumiCurtis.webp'),
(305, 'Riza Hawkeye', 27, 'Card_RizaHawkeye.webp'),
(306, 'Yuzu Aihara', 122, 'Card_YuzuAihara.webp'),
(307, 'Mei Aihara', 122, 'Card_MeiAihara.webp'),
(308, 'Rui Tachibana', 123, 'Card_RuiTachibana.webp'),
(309, 'Hina Tachibana', 123, 'Card_HinaTachibana.webp'),
(310, 'Narberal Gamma', 83, 'Card_NarberalGamma.webp'),
(311, 'Solution Epsilon', 83, 'Card_SolutionEpsilon.webp'),
(312, 'Milim Nava', 50, 'Card_MilimNava.webp'),
(313, 'Shuna', 50, 'Card_Shuna.webp'),
(314, 'Shion', 50, 'Card_Shion.webp'),
(315, 'Motoko Kusanagi', 124, 'Card_MotokoKusanagi.webp'),
(316, 'Suzune Horikita', 126, 'Card_SuzuneHorikita.webp'),
(317, 'Kikyo Kushida', 126, 'Card_KikyoKushida.webp'),
(318, 'Honami Ichinose', 126, 'Card_HonamiIchinose.webp'),
(319, 'Kei Karuizawa', 126, 'Card_KeiKaruizawa.webp'),
(320, 'Mamimi Samejima', 127, 'Card_MamimiSamejima.webp'),
(321, 'Haruko Haruhara', 127, 'Card_HarukoHaruhara.webp'),
(322, 'Hidomi Hibajiri', 127, 'Card_HidomiHibajiri.webp'),
(323, 'Kana Koumoto', 127, 'Card_KanaKoumoto.webp'),
(324, 'Julia Jinyu', 127, 'Card_JuliaJinyu.webp'),
(325, 'Hinae Hibajiri', 127, 'Card_HinaeHibajiri.webp'),
(326, 'Yuria Harudera', 82, 'Card_YuriaHarudera.webp'),
(327, 'Ai Hayasaka', 3, 'Card_AiHayasaka.webp'),
(328, 'Miko Iino', 3, 'Card_MikoIino.webp'),
(329, 'Mugino Shizuri', 44, 'Card_MuginoShizuri.webp'),
(330, 'Hitagi Senjougahara', 71, 'Card_HitagiSenjougahara.webp'),
(331, 'Akatsuki', 128, 'Card_Akatsuki.webp'),
(332, 'Henrietta', 128, 'Card_Henrietta.webp'),
(333, 'Marielle', 128, 'Card_Marielle.webp'),
(334, 'Fine Forte', 92, 'Card_FineForte.webp'),
(335, 'Prax Conrad', 92, 'Card_PraxConrad.webp'),
(336, 'Shouko Nishimiya', 129, 'Card_ShoukoNishimiya.webp'),
(337, 'Yuzuru Nishimiya', 129, 'Card_YuzuruNishimiya.webp'),
(338, 'Naoka Ueno', 129, 'Card_NaokaUeno.webp'),
(339, 'Rei Hino', 125, 'Card_ReiHino.webp'),
(340, 'Makoto Kino', 125, 'Card_MakotoKino.webp'),
(341, 'Usagi Tsukino', 125, 'Card_UsagiTsukino.webp'),
(342, 'Ami Mizuno', 125, 'Card_AmiMizuno.webp'),
(343, 'Minako Aino', 125, 'Card_MinakoAino.webp'),
(344, 'Shinobu Kochou', 55, 'Card_ShinobuKochou.webp'),
(345, 'Kanao Tsuyuri', 55, 'Card_KanaoTsuyuri.webp'),
(346, 'Mitsuri Kanroji', 55, 'Card_MitsuriKanroji.webp'),
(347, 'Sayu Ogiwara', 130, 'Card_SayuOgiwara.webp'),
(348, 'Airi Gotou', 130, 'Card_AiriGotou.webp'),
(349, 'Yuzuha Mishima', 130, 'Card_YuzuhaMishima.webp'),
(350, 'Asami Yuuki', 130, 'Card_AsamiYuuki.webp'),
(351, 'Kei Shirogane', 3, 'Card_KeiShirogane.webp'),
(352, 'Tohru Honda', 131, 'Card_TohruHonda.webp'),
(353, 'Azusa Aizawa', 132, 'Card_AzusaAizawa.webp'),
(354, 'Tornado/Tatsumaki', 133, 'Card_TornadoTatsumaki.webp'),
(355, 'Rikka Takarada', 134, 'Card_RikkaTakarada.webp'),
(356, 'Aisha Clanclan', 135, 'Card_AishaClanclan.webp'),
(357, 'Melfina', 135, 'Card_Melfina.webp'),
(358, 'Suzuka', 135, 'Card_Suzuka.webp'),
(359, 'Hilda', 135, 'Card_Hilda.webp'),
(360, 'Elizabeth Liones', 38, 'Card_ElizabethLiones.webp'),
(361, 'Diane', 38, 'Card_Diane.webp'),
(362, 'Merlin', 38, 'Card_Merlin.webp'),
(363, 'Lucifer', 136, 'Card_Lucifer.webp'),
(364, 'Belial', 136, 'Card_Belial.webp'),
(365, 'Asmodeus', 136, 'Card_Asmodeus.webp'),
(366, 'Kimura no Tsuma', 137, 'Card_KimuranoTsuma.webp'),
(367, 'Charlotte Hazelrink', 138, 'Card_CharlotteHazelrink.webp'),
(368, 'Sylvia Van Hossen', 138, 'Card_SylviaVanHossen.webp'),
(369, 'Seika Hojoin', 138, 'Card_SeikaHojoin.webp'),
(370, 'Georgie Saikawa', 48, 'Card_GeorgieSaikawa.webp'),
(371, 'Sasakibe', 48, 'Card_Sasakibe.webp'),
(372, 'Kobayashi-san', 48, 'Card_Kobayashi-san.webp'),
(373, 'Shirley Fenette', 139, 'Card_ShirleyFenette.webp'),
(374, 'Kallen Kozuki', 139, 'Card_KallenKozuki.webp'),
(375, 'Gamo-chan', 140, 'Card_Gamo-chan.webp'),
(376, 'Nagatoro', 140, 'Card_Nagatoro.webp'),
(377, 'Yoshi', 140, 'Card_Yoshi.webp'),
(378, 'Sakura', 140, 'Card_Sakura.webp'),
(379, 'President', 140, 'Card_President.webp'),
(380, 'Revy', 141, 'Card_Revy.webp'),
(381, 'Komi-san', 142, 'Card_Komi-san.webp'),
(382, 'Najimi Osana', 142, 'Card_NajimiOsana.webp'),
(383, 'Ren Yamai', 142, 'Card_RenYamai.webp'),
(384, 'Omoharu Nakanaka', 142, 'Card_OmoharuNakanaka.webp'),
(385, 'Alisa', 143, 'Card_Alisa.webp'),
(386, 'Katerina Solensan', 143, 'Card_KaterinaSolensan.webp'),
(387, 'Coffee', 143, 'Card_Coffee.webp'),
(388, 'Stella Bonnaro', 143, 'Card_StellaBonnaro.webp'),
(389, 'Houki Shinonono', 144, 'Card_HoukiShinonono.webp'),
(390, 'Cecilia Alcott', 144, 'Card_CeciliaAlcott.webp'),
(391, 'Lingyin Huang', 144, 'Card_LingyinHuang.webp'),
(392, 'Charlotte Dunois', 144, 'Card_CharlotteDunois.webp'),
(393, 'Laura Bodewig', 144, 'Card_LauraBodewig.webp'),
(394, 'Chifuyu Orimura', 144, 'Card_ChifuyuOrimura.webp'),
(395, 'Tatenashi Sarashiki', 144, 'Card_TatenashiSarashiki.webp'),
(396, 'Kanzashi Sarashiki', 144, 'Card_KanzashiSarashiki.webp'),
(397, 'Madoka Orimura', 144, 'Card_MadokaOrimura.webp'),
(398, 'Squall Meusel', 144, 'Card_SquallMeusel.webp'),
(399, 'Liscia Elfrieden', 145, 'Card_LisciaElfrieden.webp'),
(400, 'Aisha Udgard', 145, 'Card_AishaUdgard.webp'),
(401, 'Juna Doma', 145, 'Card_JunaDoma.webp'),
(402, 'Kaede Foxia', 145, 'Card_KaedeFoxia.webp'),
(403, 'Excel Walter', 145, 'Card_ExcelWalter.webp'),
(404, 'Carla Vargas', 145, 'Card_CarlaVargas.webp'),
(405, 'Elisha Elfrieden', 145, 'Card_ElishaElfrieden.webp'),
(406, 'Maria Euphoria', 145, 'Card_MariaEuphoria.webp'),
(407, 'Jeanne Euphoria', 145, 'Card_JeanneEuphoria.webp'),
(408, 'Eris', 146, 'Card_Eris.webp'),
(409, 'Manami Kinjou', 146, 'Card_ManamiKinjou.webp'),
(410, 'Aoi Futaba', 146, 'Card_AoiFutaba.webp'),
(411, 'Melwin', 146, 'Card_Melwin.webp'),
(412, 'Kuune', 146, 'Card_Kuune.webp'),
(413, 'Chaika', 146, 'Card_Chaika.webp'),
(414, 'JACK', 146, 'Card_JACK.webp'),
(415, 'Durel', 146, 'Card_Durel.webp'),
(416, 'Kana Kojima', 147, 'Card_KanaKojima.webp'),
(417, 'Hikari Hazakura', 147, 'Card_HikariHazakura.webp'),
(418, 'Chizuru Tachibana', 147, 'Card_ChizuruTachibana.webp'),
(419, 'Mayu Matsukaze', 147, 'Card_MayuMatsukaze.webp'),
(420, 'Rin Namiki', 148, 'Card_RinNamiki.webp'),
(421, 'Emily Orange', 148, 'Card_EmilyOrange.webp'),
(422, 'Misa Aoi', 148, 'Card_MisaAoi.webp'),
(423, 'Kuromaru Manpuku', 148, 'Card_KuromaruManpuku.webp'),
(424, 'Kamui Kurenai', 148, 'Card_KamuiKurenai.webp'),
(425, 'Naraku Mamiya', 148, 'Card_NarakuMamiya.webp'),
(426, 'Jennifer Peach', 148, 'Card_JenniferPeach.webp'),
(427, 'Pan Ziyu', 148, 'Card_PanZiyu.webp'),
(428, 'Manatsu Shiraishi', 148, 'Card_ManatsuShiraishi.webp'),
(429, 'Kaguya Shijyuin', 148, 'Card_KaguyaShijyuin.webp'),
(430, 'Pan Dina', 148, 'Card_PanDina.webp'),
(431, 'Yuzu Midorikawa', 148, 'Card_YuzuMidorikawa.webp'),
(432, 'Fuka Tamaki', 148, 'Card_FukaTamaki.webp'),
(433, 'Inori Misuda', 148, 'Card_InoriMisuda.webp'),
(434, 'Nozomi Kaminashi', 149, 'Card_NozomiKaminashi.webp'),
(435, 'Sayaka Miyata', 149, 'Card_SayakaMiyata.webp'),
(436, 'Kazane Aoba', 149, 'Card_KazaneAoba.webp'),
(437, 'Non Toyoguchi', 149, 'Card_NonToyoguchi.webp'),
(438, 'Mio Kusakai', 149, 'Card_MioKusakai.webp'),
(439, 'Hanabi Kawai', 149, 'Card_HanabiKawai.webp'),
(440, 'Rin Rokudo', 149, 'Card_RinRokudo.webp'),
(441, 'Usagi Tsukishita', 149, 'Card_UsagiTsukishita.webp'),
(442, 'Kotone Fujisaki', 149, 'Card_KotoneFujisaki.webp'),
(443, 'Yuko Ooshima', 149, 'Card_YukoOoshima.webp'),
(444, 'Atsuko Yoshida', 149, 'Card_AtsukoYoshida.webp'),
(445, 'Miku Kobayakawa', 149, 'Card_MikuKobayakawa.webp'),
(446, 'Hitomi Hokuto', 149, 'Card_HitomiHokuto.webp'),
(447, 'Ao-chan', 150, 'Card_Ao-chan.webp'),
(448, 'Lala Satalin Deviluke', 151, 'Card_LalaSatalinDeviluke.webp'),
(449, 'Haruna Sairenji', 151, 'Card_HarunaSairenji.webp'),
(450, 'Momo Belia Deviluke', 151, 'Card_MomoBeliaDeviluke.webp'),
(451, 'Nana Astar Deviluke', 151, 'Card_NanaAstarDeviluke.webp'),
(452, 'Golden Darkness', 151, 'Card_GoldenDarkness.webp'),
(453, 'Yui Kotegawa', 151, 'Card_YuiKotegawa.webp'),
(454, 'Mikan Yuuki', 151, 'Card_MikanYuuki.webp'),
(455, 'Run Elsie Jewelria', 151, 'Card_RunElsieJewelria.webp'),
(456, 'Risa Momioka', 151, 'Card_RisaMomioka.webp');
