INSERT IGNORE INTO cardtypes (ctid, ctname) VALUES
(1, 'Re:Zero'),
(2, 'DARLING in the FRANXX'),
(3, 'KAGUYA-SAMA: LOVE IS WAR'),
(4, 'KonoSuba'),
(5, 'Akame ga Kill!'),
(6, 'Attack on Titan'),
(7, 'Fairy Tail'),
(8, 'Boku wa Tomodachi ga Sukunai'),
(9, 'Neon Genesis Evangelion'),
(10, 'Kakegurui'),
(11, 'Bleach'),
(12, 'Noragami'),
(13, 'Food Wars!'),
(14, 'Naruto'),
(15, 'My Hero Academia'),
(16, 'Heavens Lost Property'),
(17, 'Sakurasou no Pet na Kanojo'),
(18, 'Plastic Memories'),
(19, 'Angel Beats!'),
(20, 'Nisekoi'),
(21, 'One Piece'),
(22, 'Date a Live'),
(23, 'Rosario + Vampire'),
(24, 'Trinity Seven'),
(25, 'Dr. Stone'),
(26, 'Sword Art Online'),
(27, 'Fullmetal Alchemist'),
(28, 'The Testament of Sister New Devil'),
(29, 'Kuroko no Basuke'),
(30, 'Highschool DxD'),
(31, 'Charlotte'),
(32, 'The Rising Of The Shield Hero'),
(33, 'Highscool of the Dead'),
(35, 'Dragon Ball'),
(36, 'Angels of Death'),
(37, 'Code Geass'),
(38, 'Seven deadly sins'),
(39, 'Daily Life With A Monster Girl'),
(40, 'Assassination Classroom'),
(41, 'Your Lie in April'),
(42, 'Undefeated Bahamut Chronicle'),
(43, 'Initial D'),
(44, 'A Certain Scientific Railgun'),
(45, 'A Certain Magical Index'),
(46, 'The Asterisk War'),
(47, 'Tokyo Ghoul'),
(48, 'Miss Kobayashis Dragon Maid'),
(49, 'Guilty Crown'),
(50, 'That Time I Got Reincarnated as a Slime'),
(51, 'Rent-A-Girlfriend'),
(52, 'Fate'),
(53, 'Death Note'),
(54, 'Owari no Seraph'),
(55, 'Demon Slayer'),
(56, 'Violet Evergarden'),
(57, 'Kuma Kuma Kuma Bear'),
(58, 'Sabagebu!'),
(59, 'DanMachi'),
(60, 'Bunny Girl Senpai'),
(61, 'Tonikaku Kawaii'),
(62, 'Fire Force'),
(63, 'The Irregular at Magic High School'),
(64, 'Strike The Blood'),
(65, 'Black Clover'),
(66, 'Majo No Tabitabi'),
(67, 'Uzaki-Chan Wants To Hang Out!'),
(68, 'The Quintessential Quintuplets'),
(69, 'Horimiya'),
(70, 'Show By Rock!!'),
(71, 'Monogatari Series'),
(72, 'Kill la Kill'),
(73, 'Promare'),
(74, 'Land of the Lustrous'),
(75, 'Akudama Drive'),
(76, 'Hellsing Ultimate'),
(77, 'Kara no Kyoukai'),
(78, 'No Game No Life'),
(79, 'Mushoku Tensei'),
(80, 'JoJos Bizarre Adventure'),
(81, 'Yuunas Haunted Hot Springs'),
(82, 'The Fruit of Grisaia'),
(83, 'Overlord'),
(84, 'Watamote'),
(85, 'How Not to Summon a Demon Lord'),
(86, 'Redo of Healer'),
(87, 'Love, Chunibyo & Other Delusions!'),
(88, 'Another'),
(89, 'Oreshura'),
(90, 'Goblin Slayer'),
(91, 'Uma Musume'),
(92, 'Back Arrow'),
(93, 'Wonder Egg Priority'),
(94, 'Spice and Wolf'),
(95, 'Hokuto no Ken'),
(96, 'Mirai Nikki'),
(97, 'Darker than Black'),
(98, 'Kabaneri of the Iron Fortress'),
(99, 'Kyokou Suiri'),
(100, 'Welcome to the N.H.K.'),
(101, 'Shimoneta'),
(102, 'Mysterious Girlfriend X'),
(103, 'Jormungand'),
(104, 'How Heavy are the Dumbbells You Lift?'),
(105, 'Bungo Stray Dogs'),
(106, 'Hanasaku Iroha'),
(107, 'Problem Children are Coming from Another World Arent They?'),
(108, 'Space Dandy'),
(109, 'Higurashi'),
(110, 'Rokka: Braves of the Six Flowers'),
(111, 'Bofuri'),
(112, 'Arcade Gamer Fubuki'),
(113, 'WorldEnd'),
(114, 'Claymore'),
(115, 'Tenga Toppa Gurren Lagann'),
(116, 'Arifureta'),
(117, 'Cowboy Bebop'),
(118, 'Cautious Hero'),
(119, 'Serial Experiments Lain'),
(120, 'Sankarea'),
(121, 'Magical Sempai'),
(122, 'Citrus'),
(123, 'Domestic Girlfriend'),
(124, 'Ghost in the Shell'),
(125, 'Sailor Moon'),
(126, 'Classroom of the Elite'),
(127, 'Fooly Cooly'),
(128, 'Log Horizon'),
(129, 'A Silent Voice'),
(130, 'Higehiro'),
(131, 'Fruits Basket'),
(132, 'Ive Been Killing Slimes for 300 Years and Maxed Out My Level'),
(133, 'One Punch Man'),
(134, 'SSSS Gridman'),
(135, 'Outlaw Star'),
(136, 'Sins: The Seven Deadly Sins'),
(137, 'Azumanga Daioh'),
(138, 'Princess Lover!'),
(139, 'Code Geass'),
(140, 'Ijiranaide, Nagatoro-san'),
(141, 'Black Lagoon'),
(142, 'Komi Cant Comunicate'),
(143, 'Cowboy Bebop'),
(144, 'Infinite Stratos'),
(145, 'How a Realist Hero Rebuilt the Kingdom'),
(146, 'Cat Planet Cuties'),
(147, 'Why the Hell are You Here, Teacher!?'),
(148, 'Kandagawa Jet Girls'),
(149, 'KEIJO!!!!!!!!'),
(150, 'Ao-chan Cant Study'),
(151, 'To Love Ru');
